### ISSUE TITLE
Find a way to avoid orange blinking in taskbar.

### ISSUE THREAD

**Issue by KevinVG207** [KevinVG207/UmaLauncher#149]
Using the Chromium webdriver, carrotjuicer code forces focus onto the browser tabs every training turn.
With taskbar set to auto-hide, this causes the taskbar to keep popping up (because the taskbar icon blinks orange?)
Maybe there's some win32api way to avoid this behavior.

Uma Discord message from the problem user: https://discord.com/channels/425124932398350338/1048714273368592395/1134171092781633607

![image](https://github.com/KevinVG207/UmaLauncher/assets/19467234/7b59059e-8d03-4604-9518-f143b5b3af9b)

**Comment by petooshoque** [comment]
LOW PRIORITY???!?!?!
I wish you a blinking evening.

**Comment by KevinVG207** [comment]
@petooshoque The current workaround is too choose Firefox as the browser in the preferences. This behavior is unique to Chromium.

**Comment by petooshoque** [comment]
Thanks.

**Comment by KevinVG207** [comment]
@petooshoque A fix was implemented and an update will be released today.
