### ISSUE TITLE
OpenVPN Profile Issues

### ISSUE THREAD

**Issue by rekyuu** [KevinVG207/UmaLauncher#288]
The VPN process seems to fail when an OpenVPN configuration internally references files. Here's the config provided by Mullvad VPN:

```
client
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
remote-cert-tls server
ping 10
ping-restart 60
sndbuf 524288
rcvbuf 524288
cipher AES-256-GCM
tls-cipher TLS-DHE-RSA-WITH-AES-256-GCM-SHA384
proto udp
auth-user-pass mullvad_userpass.txt # <---------------------- HERE
ca mullvad_ca.crt # <---------------------------------------- HERE
service mullvadopenvpn
block-outside-dns
remote-random
remote <ip> <port>
remote <ip> <port>
```

These files are located within the profile's folder:

```
C:\Users\rekyuu\OpenVPN\config\mullvad_jp_tyo
├── mullvad_ca.crt
├── mullvad_jp_tyo.ovpn
└── mullvad_userpass.txt
```

As per https://github.com/KevinVG207/UmaLauncher/blob/main/umalauncher/vpn.py#L248, when running `"C:\Program Files\OpenVPN\bin\openvpn.exe" --config "C:\Users\rekyuu\OpenVPN\config\mullvad_jp_tyo\mullvad_jp_tyo.ovpn"` the process fails, as it tries referencing files within the current working directory instead of within the configuration folder. However, if you ran `"C:\Program Files\OpenVPN\bin\openvpn.exe" --cd "C:\Users\rekyuu\OpenVPN\config\mullvad_jp_tyo" --config "mullvad_jp_tyo.ovpn"`, the process succeeds. This process needs to be run as administrator though.

Alternatively, if the user is running the OpenVPN GUI, you can also send `"C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --command connect "mullvad_jp_tyo"`, but I don't see a way to confirm connection using this command. You could also run `"C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --connect "mullvad_jp_tyo"` if the GUI isn't running yet.

**Comment by rekyuu** [comment]
I made a PR to make this work, but I develop on Linux so I'm not able to test it (also I'm a little lazy). Not sure if the updated logic is up to standards either but hopefully it's a start.

**Comment by KevinVG207** [comment]
@rekyuu Thanks for your contribution! I'll test it and get it added soon.
